language: java
jdk: openjdk8
sudo: false

cache:
 directories:
  - $HOME/.gradle/caches

branches:
 only:
  - master

install: skip

script:
 - echo "include 'plugin'" > settings.gradle
 - ./gradlew clean :plugin:publishMavenJavaPublicationToMavenLocal
 - echo "include 'plugin', 'examples'" > settings.gradle
 - ./gradlew :examples:run
 - ./gradlew bintrayUpload